services:
  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: DB_ecommerce
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d DB_ecommerce"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: ecommerce-demo-app:latest
    container_name: ecommerce_app
    depends_on:
      db:
        condition: service_healthy
    environment:
      PORT: 10000
      SPRING_PROFILES_ACTIVE: dev
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/DB_ecommerce
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: 123456
      APP_SECURITY_COOKIE_SECURE: "false"
    ports:
      - "10000:10000"

volumes:
  postgres_data:
